import { relative } from 'node:path';

export const CONFIG_FILE_PATTERN = /^(.+)\.(ts|js|mjs)$/;

/**
 * Virtual entry that re-exports every config file's default export under its
 * config key. Bundling this with esbuild collapses the whole config graph
 * (which transitively imports app models, listeners, policies, ...) into a
 * single file while preserving live class references — unlike the old JSON
 * manifest, which serialized classes to null.
 */
export function generateConfigBundleEntry(files: string[]): string {
  const lines: string[] = [];
  const entries: string[] = [];

  files.forEach((file, index) => {
    const key = file.match(CONFIG_FILE_PATTERN)?.[1];
    if (!key) {
      return;
    }

    lines.push(`import * as $m${index} from './${file}';`);
    entries.push(`${JSON.stringify(key)}: ($m${index}.default ?? $m${index})`);
  });

  lines.push(`export default { ${entries.join(', ')} };`);
  return lines.join('\n');
}

export interface FullBundleEntryOptions {
  /** Absolute project root (used to load .env before config modules run). */
  root: string;
  /** Directory the generated entry file will be written to. */
  entryDir: string;
  /** Absolute path of the application entry (e.g. src/main.ts). */
  appEntry: string;
  /** Config file names inside <root>/config (may be empty). */
  configFiles: string[];
}

function relativeImport(fromDir: string, target: string): string {
  const rel = relative(fromDir, target).split('\\').join('/');
  return rel.startsWith('.') ? rel : `./${rel}`;
}

/**
 * Entry module for `pondoknusa build --full`. Everything is dynamic-imported
 * so ordering survives bundling: .env loads first, then config modules
 * evaluate (their env() calls see .env values), the merged tree is registered
 * with ConfigServiceProvider's build-time slot, and only then does the
 * application entry run. The result is a single file containing framework,
 * app code, and config — one copy of every class, no per-file imports at
 * boot.
 */
export function generateFullBundleEntry(options: FullBundleEntryOptions): string {
  const { root, entryDir, appEntry, configFiles } = options;
  const lines: string[] = [
    '// AUTO-GENERATED by `pondoknusa build --full` — do not edit.',
    `import { loadProjectEnv, registerCachedConfig } from '@pondoknusa/config';`,
    '',
    `await loadProjectEnv(${JSON.stringify(root)});`,
  ];

  if (configFiles.length > 0) {
    const imports = configFiles.map(
      (file) => `import(${JSON.stringify(relativeImport(entryDir, `${root}/config/${file}`))})`,
    );
    lines.push(
      '',
      `const [${configFiles.map((_, index) => `$m${index}`).join(', ')}] = await Promise.all([`,
      `  ${imports.join(',\n  ')},`,
      ']);',
    );

    const entries = configFiles.map((file, index) => {
      const key = file.match(CONFIG_FILE_PATTERN)?.[1] ?? file;
      return `${JSON.stringify(key)}: ($m${index}.default ?? $m${index})`;
    });
    lines.push('', `registerCachedConfig({ ${entries.join(', ')} });`);
  }

  lines.push('', `await import(${JSON.stringify(relativeImport(entryDir, appEntry))});`, '');
  return lines.join('\n');
}

/**
 * esbuild plugin for --full builds: inline @pondoknusa/* packages and app
 * code, but keep third-party npm packages (pg, redis, native addons like
 * oracledb, ...) external so they resolve from node_modules at runtime.
 */
export function createFullBundlePlugin(): {
  name: string;
  setup: (build: {
    onResolve: (
      options: { filter: RegExp },
      callback: (args: { path: string }) => { external: boolean } | undefined,
    ) => void;
  }) => void;
} {
  return {
    name: 'pondoknusa-full-bundle',
    setup(build) {
      build.onResolve({ filter: /^[^./]/ }, (args) => {
        const path = args.path;
        if (
          path.startsWith('@pondoknusa/')
          || path.startsWith('/')
          || /^[a-zA-Z]:[\\/]/.test(path)
          || path.startsWith('\\\\')
        ) {
          // Framework packages and absolute paths are bundled.
          return undefined;
        }

        return { external: true };
      });
    },
  };
}
